Add configurable timeout for ensure alive
snoyberg/keter pull request #220
Opened 2021-05-12 18:47 UTC by jappeace

This allows certain application to have a long boot cycle while the
old application is still running.
A specific use case for supercede for example is running migrations
before switching.

Add comment it's in microseconds

Fix import styling

2021-05-12 18:49 UTC, jappeace commented
I tested this with an executable like this:

```
#!/usr/bin/env bash

set -xe

sleep 10

nc -l "$PORT"
```


and then modify the new field below and higher than 10 seconds.

2021-06-09 18:48 UTC, jappeace commented
@mmzx could you look into this?

2021-06-09 22:01 UTC, mmzx commented
@jappeace , certainly yes. Give me to do that over weekend please.

2021-06-10 14:30 UTC, jappeace commented
Thank you, it's appreciated!

2021-06-14 21:49 UTC, mmzx commented
@jappeace What would be a/some test scenario(s) to check the changes do what we expect from them?

2021-06-14 22:12 UTC, mmzx requested changes
I think the changes are actually fine.
Would you perhaps extend the example configuration file as well? In the meantime I am giving it a shot...

2021-06-14 22:12 UTC, mmzx commented on Keter/App.hs
> +        mapM_ ensureAlive  runningWebapps
This is probably an extra white-space.

2021-07-08 09:02 UTC, jappeace commented on Keter/App.hs
> +        mapM_ ensureAlive  runningWebapps
I removed the whitespace.

2021-07-08 09:03 UTC, jappeace commented
@mmzx I added an example in fede259

2021-08-04 11:10 UTC, merged

2021-08-04 11:11 UTC, mmzx commented
Sweet, thanks!